version: "3.9"
name: back-bp
services:
  # server:
  #   build: .
  #   ports:
  #     - "${PORT}:5000"
  #   environment:
  #     - PORT
  #     - API_URL
  #     - CLIENT_URL
  #     - DATABASE_URL
  #     - GOOGLE_CLIENT_ID
  #     - GOOGLE_CLIENT_SECRET
  #     - SESSION_SECRET
  #     - SESSION_COOKIE_NAME
  #     - SMTP_HOST
  #     - SMTP_USER
  #     - SMTP_PASSWORD
  #     - SMTP_PORT
  #     - SMTP_SECURE
  #   depends_on:
  #     - db
  db:
    image: postgres
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"

volumes:
  db:
