version: "3.9"
name: back-bp
services:
  server:
    profiles: ["prod"]
    build: .
    ports:
      - "${PORT}:5000"
    environment:
      # Probably not up to date (check .env)
      - PORT
      - API_URL
      - CLIENT_URL
      - DATABASE_URL=${DATABASE_PROVIDER}://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - SESSION_SECRET
      - SESSION_COOKIE_NAME
      - SMTP_HOST
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_PORT
      - SMTP_SECURE
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes: 
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"
  minio:
    image: bitnami/minio
    restart: always
    volumes:
      - minio:/data
    environment:
      - MINIO_FORCE_NEW_KEYS=yes
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    ports:
      - ${MINIO_CONSOLE_PORT}:9001
      - ${MINIO_PORT}:9000
  # TESTS
  db-test:
    image: postgres
    restart: always
    profiles: ["test"]
    environment:
      - POSTGRES_PASSWORD=${TESTS_E2E_DATABASE_PASSWORD}
      - POSTGRES_USER=${TESTS_E2E_DATABASE_USER}
      - POSTGRES_DB=${TESTS_E2E_DATABASE_NAME}
    ports:
      - "${TESTS_E2E_DATABASE_PORT}:5432"
  s3-test:
    image: bitnami/minio
    restart: always
    profiles: ["test"]
    environment:
      - MINIO_ROOT_USER=${TESTS_E2E_S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${TESTS_E2E_S3_SECRET_KEY}
    ports:
      - ${TESTS_E2E_S3_PORT}:9000
      - ${TESTS_E2E_S3_CONSOLE_PORT}:9001

volumes:
  db:
  minio:
